### ISSUE TITLE
Open Notificaties background workers deployment is missing

### ISSUE THREAD

**Issue by sergei-maertens** [open-zaak/charts#3]
The chart deploys RabbitMQ & the web service for ON, but the Celery worker for ON which actually sends the notifications to the subscriptions is missing.

Ansible equivalent is: https://github.com/open-zaak/ansible-collection/blob/main/roles/open_notificaties_k8s/templates/celery.yml.j2

**Comment by andyverberne** [comment]
I am currently working on this. Expecting a fix end of this week.
